### ISSUE TITLE
Fav icon is from the twitter twemoji set and is not attributed at all

### ISSUE THREAD

**Issue by cfulton** [nbnsucks/nbnsucks.github.io#1]
The "Angry face" emoji used for the fav icon is part of the twitter twemoji set. 

To use the emoji you'll have to give attribution as set in the readme. https://github.com/twitter/twemoji#attribution-requirements

**Comment by nbnsucks** [comment]
Done - see https://nbnsucks.com/README.md or
https://github.com/nbnsucks/nbnsucks.github.io/blob/master/README.md

Let me know if I haven't done this right ;-)

**Comment by cfulton** [comment]
Yep that is all that they asked for.
